# Generated by Django 5.0.3 on 2024-03-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminmodel',
            fields=[
                ('Admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Phonenumber', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Admin_table',
            },
        ),
        migrations.CreateModel(
            name='Maincategorymodel',
            fields=[
                ('Maincategory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Maincategory', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Maincategory_table',
            },
        ),
        migrations.CreateModel(
            name='Subcategorymodel',
            fields=[
                ('Subcategory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Subcategory', models.CharField(max_length=200)),
                ('Maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.maincategorymodel')),
            ],
            options={
                'db_table': 'Subcategory_table',
            },
        ),
    ]
