# Generated by Django 5.0.3 on 2024-03-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_maincategorymodel_image_subcategorymodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
