# Generated by Django 5.0.3 on 2024-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_delete_subcategorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='Admin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
