# Generated by Django 5.0.3 on 2024-03-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citymodel',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eventmodel',
            fields=[
                ('Event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Event', models.CharField(max_length=250)),
                ('Description', models.TextField()),
                ('start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statemodel',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Itemmodel',
            fields=[
                ('Item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Item_name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Price', models.FloatField()),
                ('Quantity', models.CharField(max_length=200)),
                ('Start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.subcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Discountmodel',
            fields=[
                ('Discount_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Discount', models.CharField(max_length=200)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.eventmodel')),
                ('Item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.itemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantmodel',
            fields=[
                ('Restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Restaurant_name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('License', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Discription', models.TextField()),
                ('Phone_no', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='')),
                ('host_status', models.CharField(max_length=100)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.citymodel')),
            ],
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.restaurantmodel'),
        ),
        migrations.AddField(
            model_name='citymodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.statemodel'),
        ),
    ]
