# Generated by Django 5.0.3 on 2024-03-25 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_subcategorymodel_maincategory'),
        ('restaurantapp', '0002_alter_citymodel_table_alter_discountmodel_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='Image',
            field=models.ImageField(null=True, upload_to='subcat/'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='Rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.maincategorymodel'),
        ),
    ]
