# Generated by Django 5.0.3 on 2024-04-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_itemmodel_image_itemmodel_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='is_in_wishlist',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
