# Generated by Django 5.0.3 on 2024-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_itemmodel_is_in_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couponmodel',
            fields=[
                ('Coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('Coupon_code', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(null=True)),
                ('minimum_amnt', models.IntegerField()),
            ],
            options={
                'db_table': 'Coupon',
            },
        ),
    ]
