# Generated by Django 5.0.3 on 2024-03-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_deliver_time_deliveryusermodel_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='User_phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
