# Generated by Django 5.0.3 on 2024-04-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_itemmodel_is_in_wishlist'),
        ('userapp', '0003_usermodel_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlistmodel',
            fields=[
                ('Wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.itemmodel')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'Wishlist',
            },
        ),
    ]
