# Generated by Django 5.0.3 on 2024-05-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_addressmodel_city_addressmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='Address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='User_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='User_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
